# Generated by Django 2.0.13 on 2019-07-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('specie', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=150)),
            ],
        ),
    ]
